### PR TITLE
Reproduce serialization of JObject issue

### PR DESCRIPTION
**Pull request by superlogical**
This is a unit test that fails

### CODE REVIEW

**Comment by superlogical** [comment]
When I use this

````
{
  "id": "PAY-999279930X082082HK3GAKPQ",
  "blah": [
    { "hello": "world" },
    { "hello": "world" },
    { "hello": "world" }
  ]
}
````

I get 

````
Expected a TermType as a NUMBER but found OBJECT.
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at RethinkDb.Driver.Tests.ReQL.PocoTests.jakes_serilization_of_jobject_issue() in PocoTests.cs: line 65
TRACE JSON Send: Token: 2, JSON: [1,[60,[[14,["query"]],"test"]],{}]
TRACE JSON Recv: Token: 2, JSON: {"t":18,"e":4100000,"r":["Table `query.test` already exists."],"b":[]}
TRACE JSON Send: Token: 3, JSON: [1,[54,[[15,[[14,["query"]],"test"]]]],{}]
TRACE JSON Recv: Token: 3, JSON: {"t":1,"r":[{"deleted":1,"errors":0,"inserted":0,"replaced":0,"skipped":0,"unchanged":0}]}
TRACE JSON Send: Token: 4, JSON: [1,[56,[[15,[[14,["query"]],"test"]],{"Data":{"id":"PAY-999279930X082082HK3GAKPQ","blah":[{"hello":"world"},{"hello":"world"},{"hello":"world"}]}}]],{}]
TRACE JSON Recv: Token: 4, JSON: {"t":17,"r":["Expected a TermType as a NUMBER but found OBJECT."],"b":[1,"Data","blah"]}
TRACE JSON Send: Token: 5, JSON: [1,[54,[[15,[[14,["rethinkdb"]],"_debug_scratch"]]]],{}]
TRACE JSON Recv: Token: 5, JSON: {"t":1,"r":[{"deleted":0,"errors":0,"inserted":0,"replaced":0,"skipped":0,"unchanged":0}]}
TRACE Response Pump: EndOfStreamException - Unable to read beyond the end of the stream. The connection can no longer be used. ResponsePump is preparing to shutdown.
TRACE Cleaning up Response Pump awaiters for 127.0.0.1:28015
````

**Comment by superlogical** [comment]
And when I use this

````json
{
  "id": "PAY-999279930X082082HK3GAKPQ",
  "blah": [    
  ]
}
````

I get this

````
Expected between 1 and 3 elements in a raw term, but found 0.
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at RethinkDb.Driver.Tests.ReQL.PocoTests.jakes_serilization_of_jobject_issue() in PocoTests.cs: line 65
TRACE JSON Send: Token: 2, JSON: [1,[60,[[14,["query"]],"test"]],{}]
TRACE JSON Recv: Token: 2, JSON: {"t":18,"e":4100000,"r":["Table `query.test` already exists."],"b":[]}
TRACE JSON Send: Token: 3, JSON: [1,[54,[[15,[[14,["query"]],"test"]]]],{}]
TRACE JSON Recv: Token: 3, JSON: {"t":1,"r":[{"deleted":0,"errors":0,"inserted":0,"replaced":0,"skipped":0,"unchanged":0}]}
TRACE JSON Send: Token: 4, JSON: [1,[56,[[15,[[14,["query"]],"test"]],{"Data":{"id":"PAY-999279930X082082HK3GAKPQ","blah":[]}}]],{}]
TRACE JSON Recv: Token: 4, JSON: {"t":17,"r":["Expected between 1 and 3 elements in a raw term, but found 0."],"b":[1,"Data","blah"]}
TRACE JSON Send: Token: 5, JSON: [1,[54,[[15,[[14,["rethinkdb"]],"_debug_scratch"]]]],{}]
TRACE JSON Recv: Token: 5, JSON: {"t":1,"r":[{"deleted":0,"errors":0,"inserted":0,"replaced":0,"skipped":0,"unchanged":0}]}
TRACE Response Pump: EndOfStreamException - Unable to read beyond the end of the stream. The connection can no longer be used. ResponsePump is preparing to shutdown.
TRACE Cleaning up Response Pump awaiters for 127.0.0.1:28015

````

**Comment by bchavez** [comment]
hey @superlogical , I think I have a reliable fix now. Did you sign the RethinkDB CLA? 

http://rethinkdb.com/community/cla/

If you did, I'll go ahead and merge your test.

**Comment by superlogical** [comment]
````
r.db('rethink').table('contributors')
   .update({ 'count': r.row('count').add(1) })
````

**Comment by bchavez** [comment]
Awesome. Thank you!

**Comment by bchavez** [comment]
Hey @superlogical , can you give [**v2.2.9-beta-2**](https://www.nuget.org/packages/RethinkDb.Driver/2.2.9-beta-2) a try? beta-2 can pass the unit test.

**Comment by superlogical** [comment]
Thanks mate!

**Pull request merged**
