### PR TITLE
Added between support and refactored some code Fixes #52

### LINKED ISSUE #52: Added support for between
Add translation of queries like on indexes to use `Between`

- `.Where( x.Size > 5 && x.Size < 10 )`
- `.Where( x.Date < DateTime.Now && x.Date > new DateTime( 2016, 1, 1 ) )`

### PR DESCRIPTION
**Pull request by jrote1**
Before submitting your PR, please review the following checklist:

- [x] I have signed the [**RethinkDB CLA**](http://rethinkdb.com/community/cla).
- [x] **CONSIDER** adding a unit test if your PR resolves an issue.
- [x] **DO** keep pull requests small so they can be easily reviewed.
- [x] **DO** make sure unit tests pass.
- [x] **DO** make sure any public APIs are XML documented.
- [x] **DO** make sure not to introduce any compiler warnings.
- [x] **AVOID** breaking the continuous integration build.
- [x] **AVOID** making significant changes to the driver's overall architecture.

I haven't written C# for over 2 years so be kind :p I'm joking be nice a thorough. It's good to contribute again

### CODE REVIEW

**Review by bchavez — APPROVED** [review]
LGTM! 👍

**Comment by bchavez** [comment]
Hi Jake, thanks for the PR! Happy to see you again!

I'm currently on vacation traveling. I briefly looked at the PR and it looks okay! I don't have access to my dev box to test, but if the build server says it's okay we're good!

I think you still have commit access so feel free to merge if you feel it's ready for release! Ping me if you'd like me to issue a release on NuGet after merging!

Again, great to see you again Jake! Hope all is well!

Thanks,
Brian

**Comment by jrote1** [comment]
@bchavez I'm working on a bunch of additions to the Linq provider so maybe I'll pull this into a Linq improvements branch and then we can pull into master when your back from vacation. What do you think?
Hope your having a great vacation and is good to be back

**Comment by bchavez** [comment]
Hey Jake! Whichever approach you want to take is totally fine with me! I should be back around Oct 4th. 

I think the only requirement we should keep is making sure `master` is always production-ready. Being able to cut a release from `master` at any time is super powerful for quick iteration times and emergency bug fixes! 👍

**Pull request merged**
