### PR TITLE
Fix null reference exception and used JObject.FromObject before addin…

### PR DESCRIPTION
**Pull request by cadabloom**
Fix null reference exception and used JObject.FromObject before adding any objects to JArray list.
To make insert work with MapObject/Dictionaries

### CODE REVIEW

**Comment by bchavez** [comment]
Wow. Cool. First pull request. Thanks!

**Comment by bchavez** [comment]
@cadabloom , alpha4 with your PR has been pushed to NuGet, it should appear momentary after NuGet's package index gets updated. Thanks again for your PR. :+1:

**Comment by cadabloom** [comment]
@bchavez Sweet! 
There's one issue I bumped into when the result set is not an atom. It returns a type Cursor<T> but method signature expects a return type of just T. I'll try to implement a fix, hopefully this week

**Comment by cadabloom** [comment]
Some more info -- the issue above works if T is an object type, but if it is another type it throws a conversion error.

**Comment by bchavez** [comment]
@cadabloom Cool. Thank you. I haven't tried any CRUD operations yet. I'm mostly waiting for @deontologician 's java driver unit tests work to complete (should be soon). Once Josh is done with the unit test work in Java, hopefully we'll have some some intermediate JSON we can use to generate C# unit tests that should iron out the rough edges of this C# driver.

**Comment by deontologician** [comment]
I'm getting close :) I really wish Java had type inference, that's what's mostly been holding it up since the tests don't directly have type information

**Pull request merged**
