### PR TITLE
Json.NET DateParseHandling set to None

### PR DESCRIPTION
**Pull request by oliverjanik**
Failing test + extra setting on the default converter. CLA signed.

### CODE REVIEW

**Comment by bchavez** [comment]
Thanks @oliverjanik , going to take a second look at this. I'll let you know what I find out.

:headphones: :notes: [***Antiserum & Mayhem - Trippy***](https://www.youtube.com/watch?v=o95ZTp5fuF8)

**Comment by oliverjanik** [comment]
Hmm wondering why the CI failed.

**Comment by bchavez** [comment]
I *might* have a working solution for you, but I'm getting some inconsistent `Grouping` tests that sometimes pass and sometimes fail, not totally sure why yet. Still feels like a mysteirous CLR thing at the moment.

:dash: :walking: [***"Bubbles of gas in my brain... Send me off balance, it's not enough"***](https://www.youtube.com/watch?v=AS6NfeREKPk)

**Comment by bchavez** [comment]
Hey @oliverjanik, I think I got it. Waiting on CI to check PR #82.

We'll ship a new driver release tonight. Thanks for your patience.

Thanks,
Brian

:rose: :tulip: [**The Chainsmokers - Roses (feat. ROZES)**](https://www.youtube.com/watch?v=FyASdjZE0R0)

**Pull request closed without merging**
