### PR TITLE
Fixes #113, allow client-side generation of ReGrid file ids.

### LINKED ISSUE #113: Regrid: support client generated IDs for FileInfo
Perhaps in UploadOptions which is exposed by Bucket.OpenUploadStream?

### PR DESCRIPTION
**Pull request by bchavez**
Fixes #113, allow client-side generation of ReGrid file ids.

cc @oliverjanik

:evergreen_tree: :crystal_ball: **[PINES - Fate](https://www.youtube.com/watch?v=M2D7lCeVxGs)**

### CODE REVIEW

**Comment by oliverjanik** [comment]
LGTM. thanks.

**Comment by oliverjanik** [comment]
It just occurred to me, but Guid is a struct, will the driver handle default(Guid) correctly if the ForceFileId is not set?

**Comment by oliverjanik** [comment]
Looks like it works well. Empty Guid is treated as non-existent Id.

**Comment by bchavez** [comment]
It should see the default handling rule here: 

https://github.com/bchavez/RethinkDb.Driver/blob/ef07560225e9aa2d363e67830430e83ac2a60a39/Source/RethinkDb.Driver.ReGrid/FileInfo.cs#L29

:sunglasses: 

---

:last_quarter_moon: :last_quarter_moon: ***["Uh huh, you know what it is. Black and yellow..."](https://www.youtube.com/watch?v=nWAGLkyxQG0)***

**Pull request merged**
